name = "aoc"
version = "1.0.0"
description = "Advent of Code in Gleam"
licences = ["MIT"]
repository = { type = "forgejo", host = "whitespace.moe", user = "lily", repo = "gleam_aoc" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gladvent = ">= 2.2.1 and < 3.0.0"
gleam_community_maths = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
