name = "aoc"
version = "1.0.0"
description = "Advent of Code in Gleam"
licences = ["MIT"]
repository = { type = "forgejo", host = "whitespace.moe", user = "lily", repo = "gleam_aoc" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gladvent = ">= 2.2.1 and < 3.0.0"
gleam_community_maths = ">= 2.0.0 and < 3.0.0"
gleamy_structures = ">= 1.2.0 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
shellout = ">= 1.7.0 and < 2.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[gladvent.2024]
1 = { pt_1 = 1530215, pt_2 = 26800609 }

[gladvent.2025]
1 = { pt_1 = 1048, pt_2 = 6498 }
2 = { pt_1 = 23701357374, pt_2 = 34284458938 }
3 = { pt_1 = 17281, pt_2 = 171388730430281 }
4 = { pt_1 = 1372, pt_2 = 7922 }
5 = { pt_1 = 679, pt_2 = 358155203664116 }
6 = { pt_1 = 4583860641327, pt_2 = 11602774058280 }
7 = { pt_1 = 1499, pt_2 = 24743903847942 }
8 = { pt_1 = 140008, pt_2 = 9253260633 }
9 = { pt_1 = 4771532800, pt_2 = 1544362560 }
10 = { pt_1 = 444, pt_2 = 16513 }
